///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationSQLdm.BVT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the BVTRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("66deb29b-1505-4aae-ba1c-80d360e98697")]
    public partial class BVTRepo : RepoGenBaseFolder
    {
        static BVTRepo instance = new BVTRepo();
        BVTRepoFolders.ApplicationAppFolder _application;
        BVTRepoFolders.SQLdmAppFolder _sqldm;

        /// <summary>
        /// Gets the singleton class instance representing the BVTRepo element repository.
        /// </summary>
        [RepositoryFolder("66deb29b-1505-4aae-ba1c-80d360e98697")]
        public static BVTRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public BVTRepo() 
            : base("BVTRepo", "/", null, 0, false, "66deb29b-1505-4aae-ba1c-80d360e98697", ".\\RepositoryImages\\BVTRepo66deb29b.rximgres")
        {
            _application = new BVTRepoFolders.ApplicationAppFolder(this);
            _sqldm = new BVTRepoFolders.SQLdmAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("66deb29b-1505-4aae-ba1c-80d360e98697")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("c7bdee8e-d698-4d20-93b9-3dab5c46ab8b")]
        public virtual BVTRepoFolders.ApplicationAppFolder Application
        {
            get { return _application; }
        }

        /// <summary>
        /// The SQLdm folder.
        /// </summary>
        [RepositoryFolder("4d417360-c4e7-4e3d-b591-012bb11139cc")]
        public virtual BVTRepoFolders.SQLdmAppFolder SQLdm
        {
            get { return _sqldm; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class BVTRepoFolders
    {
        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("c7bdee8e-d698-4d20-93b9-3dab5c46ab8b")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtsqldmtodayInfo;
            RepoItemInfo _sqldmpaneInfo;
            RepoItemInfo _allserversInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "//form[@title~'^Idera\\ SQL\\ diagnostic\\ mana']", parentFolder, 30000, null, true, "c7bdee8e-d698-4d20-93b9-3dab5c46ab8b", "")
            {
                _txtsqldmtodayInfo = new RepoItemInfo(this, "txtSQLdmToday", ".//statusbar[@automationid='statusBar']//button[@automationid='toolBarTodayButton']/text[@caption='SQLDM Today']", 30000, null, "81683638-41e0-4e76-9d12-70a576db58c0");
                _sqldmpaneInfo = new RepoItemInfo(this, "SQLdmPane", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']//container[@controlname='contentPanel.ClientArea']/toolbar[@controltypename='HeaderStrip']/text", 30000, null, "b7d1620e-9099-41d5-bc09-7448ed529c6a");
                _allserversInfo = new RepoItemInfo(this, "AllServers", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='navigationPaneHost']/?/?/container[@controlname='NavigationPaneControl']//container[@controlname='serverGroupPanel']/tree[@controlname='userViewTreeView']/?/?/treeitem[@accessiblename='All Servers']", 30000, null, "f26804dd-9b24-4517-831e-43eef2f89e80");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c7bdee8e-d698-4d20-93b9-3dab5c46ab8b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c7bdee8e-d698-4d20-93b9-3dab5c46ab8b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtSQLdmToday item.
            /// </summary>
            [RepositoryItem("81683638-41e0-4e76-9d12-70a576db58c0")]
            public virtual Ranorex.Text txtSQLdmToday
            {
                get
                {
                    return _txtsqldmtodayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtSQLdmToday item info.
            /// </summary>
            [RepositoryItemInfo("81683638-41e0-4e76-9d12-70a576db58c0")]
            public virtual RepoItemInfo txtSQLdmTodayInfo
            {
                get
                {
                    return _txtsqldmtodayInfo;
                }
            }

            /// <summary>
            /// The SQLdmPane item.
            /// </summary>
            [RepositoryItem("b7d1620e-9099-41d5-bc09-7448ed529c6a")]
            public virtual Ranorex.Text SQLdmPane
            {
                get
                {
                    return _sqldmpaneInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SQLdmPane item info.
            /// </summary>
            [RepositoryItemInfo("b7d1620e-9099-41d5-bc09-7448ed529c6a")]
            public virtual RepoItemInfo SQLdmPaneInfo
            {
                get
                {
                    return _sqldmpaneInfo;
                }
            }

            /// <summary>
            /// The AllServers item.
            /// </summary>
            [RepositoryItem("f26804dd-9b24-4517-831e-43eef2f89e80")]
            public virtual Ranorex.TreeItem AllServers
            {
                get
                {
                    return _allserversInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The AllServers item info.
            /// </summary>
            [RepositoryItemInfo("f26804dd-9b24-4517-831e-43eef2f89e80")]
            public virtual RepoItemInfo AllServersInfo
            {
                get
                {
                    return _allserversInfo;
                }
            }
        }

        /// <summary>
        /// The SQLdmAppFolder folder.
        /// </summary>
        [RepositoryFolder("4d417360-c4e7-4e3d-b591-012bb11139cc")]
        public partial class SQLdmAppFolder : RepoGenBaseFolder
        {
            BVTRepoFolders.OverViewTabFolder _overviewtab;
            BVTRepoFolders.QueriesTabFolder _queriestab;
            BVTRepoFolders.DatabasesTabFolder _databasestab;
            BVTRepoFolders.ViewFolder _view;
            BVTRepoFolders.ServicesTabFolder _servicestab;
            RepoItemInfo _radiosummaryInfo;
            RepoItemInfo _radiodetailsInfo;
            RepoItemInfo _radiolocksInfo;
            RepoItemInfo _radioblocksInfo;
            RepoItemInfo _txtsumresponsetimeInfo;
            RepoItemInfo _txtblblockreportsInfo;
            RepoItemInfo _ddllolockstatisticsInfo;
            RepoItemInfo _txtdedetailsInfo;
            RepoItemInfo _txtsumsessionsInfo;
            RepoItemInfo _btndbcpuInfo;
            RepoItemInfo _txtsessionsInfo;
            RepoItemInfo _tabsessionsInfo;
            RepoItemInfo _tabqueriesInfo;
            RepoItemInfo _tabresourcesInfo;
            RepoItemInfo _tabdatabasesInfo;
            RepoItemInfo _tabservicesInfo;
            RepoItemInfo _tablogsInfo;
            RepoItemInfo _tabanalyzeInfo;
            RepoItemInfo _taboverviewInfo;
            RepoItemInfo _txtovtldatabasesInfo;
            RepoItemInfo _txtqueqhquerysignatureInfo;
            RepoItemInfo _tblqueryeventoccerrancesInfo;
            RepoItemInfo _btnqwquerywaitsovertimeInfo;
            RepoItemInfo _tbldbssummaryInfo;
            RepoItemInfo _tbldbstempdbsummaryInfo;
            RepoItemInfo _tbldbsconfigurationInfo;
            RepoItemInfo _tbldbsfilesInfo;
            RepoItemInfo _tbldbstablesandindexesInfo;
            RepoItemInfo _tbldbsmirroringInfo;
            RepoItemInfo _tbldbsbackupsandrestoresInfo;
            RepoItemInfo _tbldbsservicesummaryInfo;
            RepoItemInfo _tbldbsservicesqlagentjobsInfo;
            RepoItemInfo _tbldbsservicesjobhistoryInfo;

            /// <summary>
            /// Creates a new SQLdm  folder.
            /// </summary>
            public SQLdmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SQLdm", "//form[@title~'^Idera\\ SQL\\ diagnostic\\ mana']", parentFolder, 30000, null, true, "4d417360-c4e7-4e3d-b591-012bb11139cc", "")
            {
                _overviewtab = new BVTRepoFolders.OverViewTabFolder(this);
                _queriestab = new BVTRepoFolders.QueriesTabFolder(this);
                _databasestab = new BVTRepoFolders.DatabasesTabFolder(this);
                _view = new BVTRepoFolders.ViewFolder(this);
                _servicestab = new BVTRepoFolders.ServicesTabFolder(this);
                _radiosummaryInfo = new RepoItemInfo(this, "radioSummary", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Sessions']/toolbar[@automationid='sessionsTabViewsGroup']/container[@caption='']/radiobutton[1]", 30000, null, "cd1b304b-88bd-448d-84b1-a47b878dc059");
                _radiodetailsInfo = new RepoItemInfo(this, "radioDetails", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Sessions']/toolbar[@automationid='sessionsTabViewsGroup']/container[@caption='']/radiobutton[2]", 30000, null, "514075e6-e49f-4bb1-bd46-69b8d3efb092");
                _radiolocksInfo = new RepoItemInfo(this, "radioLocks", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Sessions']/toolbar[@automationid='sessionsTabViewsGroup']/container[@caption='']/radiobutton[3]", 30000, null, "d75d8732-b228-4244-aab9-8017060a5a68");
                _radioblocksInfo = new RepoItemInfo(this, "radioBlocks", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Sessions']/toolbar[@automationid='sessionsTabViewsGroup']/container[@caption='']/radiobutton[4]", 30000, null, "5a261ba9-9b18-496a-b66a-95259e538e80");
                _txtsumresponsetimeInfo = new RepoItemInfo(this, "txtSUMResponseTime", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']//container[@controlname='SessionsSummaryView']//toolbar[@controlname='responseTimeHeaderStrip']/text[@accessiblename='Response Time']", 30000, null, "663fbee2-114e-49d3-aacc-b7bf5f29bbab");
                _txtblblockreportsInfo = new RepoItemInfo(this, "txtBLBlockReports", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']/container[@controlname='SessionsBlockingView']//container[@controlname='locksDeadLocksListSplitContainer']/container[@controlname='panel1']/toolbar[@controlname='headerStrip1']/text[@accessiblename='Block Reports']", 30000, null, "80da4777-721e-46ce-9870-88266c33f818");
                _ddllolockstatisticsInfo = new RepoItemInfo(this, "ddlLOLockStatistics", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']/container[@controlname='SessionsLocksView']//toolbar[@controlname='lockStatisticsHeaderStrip']/menuitem[@accessiblename='Lock Statistics: Requests']", 30000, null, "e900c093-844d-45ca-a573-4f4964bbcb44");
                _txtdedetailsInfo = new RepoItemInfo(this, "txtDEDetails", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']//container[@controlname='SessionsDetailsView']//toolbar[@controlname='detailsHeaderStrip']/text[@accessiblename='Details']", 30000, null, "56c75828-3c30-400c-8197-47603a4c5e9a");
                _txtsumsessionsInfo = new RepoItemInfo(this, "txtSumSessions", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']//container[@controlname='SessionsSummaryView']//toolbar[@controlname='sessionsHeaderStrip']/text[@accessiblename='Sessions']", 30000, null, "725ec95a-c67a-4aa1-9d9c-b1b39927965d");
                _btndbcpuInfo = new RepoItemInfo(this, "btnDBCPU", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']//container[@controlname='CpuControl']/toolbar[@controlname='dashboardHeaderStrip']/button[@accessiblename='CPU']", 30000, null, "87ac7a77-6a65-4e6a-9ce3-8f445d777780");
                _txtsessionsInfo = new RepoItemInfo(this, "txtSessions", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Sessions']/container[@automationid='tabItemText']/text[@caption='Sessions']", 30000, null, "db6e5de0-cecb-4842-b6dc-e0d193e37d4e");
                _tabsessionsInfo = new RepoItemInfo(this, "tabSessions", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Sessions']", 30000, null, "9fad9722-6123-4984-afb3-15f14392dcbe");
                _tabqueriesInfo = new RepoItemInfo(this, "tabQueries", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Queries']", 30000, null, "081f7e8e-d6eb-4b2e-a5bf-fa6eab8b99f3");
                _tabresourcesInfo = new RepoItemInfo(this, "tabResources", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Resources']", 30000, null, "fed9413b-d907-43cb-b796-874d7dc18103");
                _tabdatabasesInfo = new RepoItemInfo(this, "tabDatabases", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Databases']", 30000, null, "434665c4-0a84-4828-b806-ebfe851ef03d");
                _tabservicesInfo = new RepoItemInfo(this, "tabServices", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Services']", 30000, null, "9d3a0b79-3b63-43a3-8a85-a01f0fc4bcb4");
                _tablogsInfo = new RepoItemInfo(this, "tabLogs", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Logs']", 30000, null, "dd78e61f-4677-45d1-b273-8ffe4a158014");
                _tabanalyzeInfo = new RepoItemInfo(this, "tabAnalyze", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Analyze']", 30000, null, "44c09e8d-d50a-40a0-8de6-9978499ee37a");
                _taboverviewInfo = new RepoItemInfo(this, "tabOverView", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Overview']", 30000, null, "08c84396-3698-49d2-be5b-5c07585b8526");
                _txtovtldatabasesInfo = new RepoItemInfo(this, "txtOVTLDatabases", ".//container[@automationid='viewContainer']/container[@automationid='viewHost']/text[@automationid='label1']", 30000, null, "b183b56d-66a9-42e1-b24d-657c5ff85e84");
                _txtqueqhquerysignatureInfo = new RepoItemInfo(this, "txtQUEQHQuerySignature", ".//statusbar[@automationid='statusBar']/container[2]/container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']//toolbar[@accessiblename='N/A']/text[@accessiblename='Query Signature:']", 30000, null, "1ac53496-5430-4106-be56-730602c18cbb");
                _tblqueryeventoccerrancesInfo = new RepoItemInfo(this, "tblQueryEventOccerrances", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']//container[@controlname='splitContainer']//table[@accessiblename='Loading...']", 30000, null, "97717507-ac04-4b57-ad21-592e9f89d219");
                _btnqwquerywaitsovertimeInfo = new RepoItemInfo(this, "btnQWQueryWaitsOverTime", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']//toolbar[@controlname='headerStrip1']/button[@accessiblename='Query Waits Over Time']", 30000, null, "4b9c1ef9-ca0e-4511-9555-ec765ea99f9f");
                _tbldbssummaryInfo = new RepoItemInfo(this, "tblDBSSummary", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']/container[@controlname='DatabasesSummaryView']//table[@accessiblerole='Table']", 30000, null, "a46dff0c-7ffe-4991-b4cc-be263d7d93ca");
                _tbldbstempdbsummaryInfo = new RepoItemInfo(this, "tblDBSTempDBSummary", "statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']/?/?/container[@controlname='DatabasesTempdbView_Fill_Panel']//table[@accessiblename='No Data Available']", 30000, null, "7d37f544-3be8-4586-8b73-df846e0d5e68");
                _tbldbsconfigurationInfo = new RepoItemInfo(this, "tblDBSConfiguration", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']//table[@accessiblerole='Table']", 30000, null, "195a2ec4-962e-4d2e-b2b7-76d747894459");
                _tbldbsfilesInfo = new RepoItemInfo(this, "tblDBSFiles", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']/container[@controlname='DatabasesFilesView']//table[@accessiblename='Loading...']", 30000, null, "8dd4598b-05d8-4588-a263-3ca1bb8adc88");
                _tbldbstablesandindexesInfo = new RepoItemInfo(this, "tblDBSTablesAndIndexes", ".//container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']/container[@controlname='DatabasesTablesIndexesView']//table[@accessiblerole='Table']", 30000, null, "00c0bfef-1197-4e2f-ae91-21982433f22a");
                _tbldbsmirroringInfo = new RepoItemInfo(this, "tblDBSMirroring", ".//container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']/container[@controlname='DatabasesBackupRestoreHistoryView']//table[@accessiblerole='Table']", 30000, null, "cb330ad6-2a18-4c2f-828f-68d91269413d");
                _tbldbsbackupsandrestoresInfo = new RepoItemInfo(this, "tblDBSBackupsAndRestores", ".//container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']/container[@controlname='DatabasesBackupRestoreHistoryView']//table[@accessiblerole='Table']", 30000, null, "44dd3d35-b3a1-4d64-b186-1a9a11f20642");
                _tbldbsservicesummaryInfo = new RepoItemInfo(this, "tblDBSServiceSummary", ".//container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']/container[@controlname='ServicesSummaryView']//table[@accessiblerole='Table']", 30000, null, "06f034e2-34f6-435b-9ed7-32dadab606c3");
                _tbldbsservicesqlagentjobsInfo = new RepoItemInfo(this, "tblDBSServiceSqlAgentJobs", ".//container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']/container[@controlname='ServicesSqlAgentJobsView']//table[@accessiblerole='Table']", 30000, null, "8d26c84a-cd04-4d47-a0ad-c92138d98a34");
                _tbldbsservicesjobhistoryInfo = new RepoItemInfo(this, "tblDBSServicesJobHistory", ".//container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']//table[@accessiblename='Loading...']/container[@accessiblename='Data Area']/container[@accessiblename='Scrolling Region']", 30000, null, "9706d0c8-814f-4644-bd54-c8058e9ffe34");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4d417360-c4e7-4e3d-b591-012bb11139cc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4d417360-c4e7-4e3d-b591-012bb11139cc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The radioSummary item.
            /// </summary>
            [RepositoryItem("cd1b304b-88bd-448d-84b1-a47b878dc059")]
            public virtual Ranorex.RadioButton radioSummary
            {
                get
                {
                    return _radiosummaryInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The radioSummary item info.
            /// </summary>
            [RepositoryItemInfo("cd1b304b-88bd-448d-84b1-a47b878dc059")]
            public virtual RepoItemInfo radioSummaryInfo
            {
                get
                {
                    return _radiosummaryInfo;
                }
            }

            /// <summary>
            /// The radioDetails item.
            /// </summary>
            [RepositoryItem("514075e6-e49f-4bb1-bd46-69b8d3efb092")]
            public virtual Ranorex.RadioButton radioDetails
            {
                get
                {
                    return _radiodetailsInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The radioDetails item info.
            /// </summary>
            [RepositoryItemInfo("514075e6-e49f-4bb1-bd46-69b8d3efb092")]
            public virtual RepoItemInfo radioDetailsInfo
            {
                get
                {
                    return _radiodetailsInfo;
                }
            }

            /// <summary>
            /// The radioLocks item.
            /// </summary>
            [RepositoryItem("d75d8732-b228-4244-aab9-8017060a5a68")]
            public virtual Ranorex.RadioButton radioLocks
            {
                get
                {
                    return _radiolocksInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The radioLocks item info.
            /// </summary>
            [RepositoryItemInfo("d75d8732-b228-4244-aab9-8017060a5a68")]
            public virtual RepoItemInfo radioLocksInfo
            {
                get
                {
                    return _radiolocksInfo;
                }
            }

            /// <summary>
            /// The radioBlocks item.
            /// </summary>
            [RepositoryItem("5a261ba9-9b18-496a-b66a-95259e538e80")]
            public virtual Ranorex.RadioButton radioBlocks
            {
                get
                {
                    return _radioblocksInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The radioBlocks item info.
            /// </summary>
            [RepositoryItemInfo("5a261ba9-9b18-496a-b66a-95259e538e80")]
            public virtual RepoItemInfo radioBlocksInfo
            {
                get
                {
                    return _radioblocksInfo;
                }
            }

            /// <summary>
            /// The txtSUMResponseTime item.
            /// </summary>
            [RepositoryItem("663fbee2-114e-49d3-aacc-b7bf5f29bbab")]
            public virtual Ranorex.Text txtSUMResponseTime
            {
                get
                {
                    return _txtsumresponsetimeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtSUMResponseTime item info.
            /// </summary>
            [RepositoryItemInfo("663fbee2-114e-49d3-aacc-b7bf5f29bbab")]
            public virtual RepoItemInfo txtSUMResponseTimeInfo
            {
                get
                {
                    return _txtsumresponsetimeInfo;
                }
            }

            /// <summary>
            /// The txtBLBlockReports item.
            /// </summary>
            [RepositoryItem("80da4777-721e-46ce-9870-88266c33f818")]
            public virtual Ranorex.Text txtBLBlockReports
            {
                get
                {
                    return _txtblblockreportsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtBLBlockReports item info.
            /// </summary>
            [RepositoryItemInfo("80da4777-721e-46ce-9870-88266c33f818")]
            public virtual RepoItemInfo txtBLBlockReportsInfo
            {
                get
                {
                    return _txtblblockreportsInfo;
                }
            }

            /// <summary>
            /// The ddlLOLockStatistics item.
            /// </summary>
            [RepositoryItem("e900c093-844d-45ca-a573-4f4964bbcb44")]
            public virtual Ranorex.MenuItem ddlLOLockStatistics
            {
                get
                {
                    return _ddllolockstatisticsInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ddlLOLockStatistics item info.
            /// </summary>
            [RepositoryItemInfo("e900c093-844d-45ca-a573-4f4964bbcb44")]
            public virtual RepoItemInfo ddlLOLockStatisticsInfo
            {
                get
                {
                    return _ddllolockstatisticsInfo;
                }
            }

            /// <summary>
            /// The txtDEDetails item.
            /// </summary>
            [RepositoryItem("56c75828-3c30-400c-8197-47603a4c5e9a")]
            public virtual Ranorex.Text txtDEDetails
            {
                get
                {
                    return _txtdedetailsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtDEDetails item info.
            /// </summary>
            [RepositoryItemInfo("56c75828-3c30-400c-8197-47603a4c5e9a")]
            public virtual RepoItemInfo txtDEDetailsInfo
            {
                get
                {
                    return _txtdedetailsInfo;
                }
            }

            /// <summary>
            /// The txtSumSessions item.
            /// </summary>
            [RepositoryItem("725ec95a-c67a-4aa1-9d9c-b1b39927965d")]
            public virtual Ranorex.Text txtSumSessions
            {
                get
                {
                    return _txtsumsessionsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtSumSessions item info.
            /// </summary>
            [RepositoryItemInfo("725ec95a-c67a-4aa1-9d9c-b1b39927965d")]
            public virtual RepoItemInfo txtSumSessionsInfo
            {
                get
                {
                    return _txtsumsessionsInfo;
                }
            }

            /// <summary>
            /// The btnDBCPU item.
            /// </summary>
            [RepositoryItem("87ac7a77-6a65-4e6a-9ce3-8f445d777780")]
            public virtual Ranorex.Button btnDBCPU
            {
                get
                {
                    return _btndbcpuInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnDBCPU item info.
            /// </summary>
            [RepositoryItemInfo("87ac7a77-6a65-4e6a-9ce3-8f445d777780")]
            public virtual RepoItemInfo btnDBCPUInfo
            {
                get
                {
                    return _btndbcpuInfo;
                }
            }

            /// <summary>
            /// The txtSessions item.
            /// </summary>
            [RepositoryItem("db6e5de0-cecb-4842-b6dc-e0d193e37d4e")]
            public virtual Ranorex.Text txtSessions
            {
                get
                {
                    return _txtsessionsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtSessions item info.
            /// </summary>
            [RepositoryItemInfo("db6e5de0-cecb-4842-b6dc-e0d193e37d4e")]
            public virtual RepoItemInfo txtSessionsInfo
            {
                get
                {
                    return _txtsessionsInfo;
                }
            }

            /// <summary>
            /// The tabSessions item.
            /// </summary>
            [RepositoryItem("9fad9722-6123-4984-afb3-15f14392dcbe")]
            public virtual Ranorex.TabPage tabSessions
            {
                get
                {
                    return _tabsessionsInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tabSessions item info.
            /// </summary>
            [RepositoryItemInfo("9fad9722-6123-4984-afb3-15f14392dcbe")]
            public virtual RepoItemInfo tabSessionsInfo
            {
                get
                {
                    return _tabsessionsInfo;
                }
            }

            /// <summary>
            /// The tabQueries item.
            /// </summary>
            [RepositoryItem("081f7e8e-d6eb-4b2e-a5bf-fa6eab8b99f3")]
            public virtual Ranorex.TabPage tabQueries
            {
                get
                {
                    return _tabqueriesInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tabQueries item info.
            /// </summary>
            [RepositoryItemInfo("081f7e8e-d6eb-4b2e-a5bf-fa6eab8b99f3")]
            public virtual RepoItemInfo tabQueriesInfo
            {
                get
                {
                    return _tabqueriesInfo;
                }
            }

            /// <summary>
            /// The tabResources item.
            /// </summary>
            [RepositoryItem("fed9413b-d907-43cb-b796-874d7dc18103")]
            public virtual Ranorex.TabPage tabResources
            {
                get
                {
                    return _tabresourcesInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tabResources item info.
            /// </summary>
            [RepositoryItemInfo("fed9413b-d907-43cb-b796-874d7dc18103")]
            public virtual RepoItemInfo tabResourcesInfo
            {
                get
                {
                    return _tabresourcesInfo;
                }
            }

            /// <summary>
            /// The tabDatabases item.
            /// </summary>
            [RepositoryItem("434665c4-0a84-4828-b806-ebfe851ef03d")]
            public virtual Ranorex.TabPage tabDatabases
            {
                get
                {
                    return _tabdatabasesInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tabDatabases item info.
            /// </summary>
            [RepositoryItemInfo("434665c4-0a84-4828-b806-ebfe851ef03d")]
            public virtual RepoItemInfo tabDatabasesInfo
            {
                get
                {
                    return _tabdatabasesInfo;
                }
            }

            /// <summary>
            /// The tabServices item.
            /// </summary>
            [RepositoryItem("9d3a0b79-3b63-43a3-8a85-a01f0fc4bcb4")]
            public virtual Ranorex.TabPage tabServices
            {
                get
                {
                    return _tabservicesInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tabServices item info.
            /// </summary>
            [RepositoryItemInfo("9d3a0b79-3b63-43a3-8a85-a01f0fc4bcb4")]
            public virtual RepoItemInfo tabServicesInfo
            {
                get
                {
                    return _tabservicesInfo;
                }
            }

            /// <summary>
            /// The tabLogs item.
            /// </summary>
            [RepositoryItem("dd78e61f-4677-45d1-b273-8ffe4a158014")]
            public virtual Ranorex.TabPage tabLogs
            {
                get
                {
                    return _tablogsInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tabLogs item info.
            /// </summary>
            [RepositoryItemInfo("dd78e61f-4677-45d1-b273-8ffe4a158014")]
            public virtual RepoItemInfo tabLogsInfo
            {
                get
                {
                    return _tablogsInfo;
                }
            }

            /// <summary>
            /// The tabAnalyze item.
            /// </summary>
            [RepositoryItem("44c09e8d-d50a-40a0-8de6-9978499ee37a")]
            public virtual Ranorex.TabPage tabAnalyze
            {
                get
                {
                    return _tabanalyzeInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tabAnalyze item info.
            /// </summary>
            [RepositoryItemInfo("44c09e8d-d50a-40a0-8de6-9978499ee37a")]
            public virtual RepoItemInfo tabAnalyzeInfo
            {
                get
                {
                    return _tabanalyzeInfo;
                }
            }

            /// <summary>
            /// The tabOverView item.
            /// </summary>
            [RepositoryItem("08c84396-3698-49d2-be5b-5c07585b8526")]
            public virtual Ranorex.TabPage tabOverView
            {
                get
                {
                    return _taboverviewInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tabOverView item info.
            /// </summary>
            [RepositoryItemInfo("08c84396-3698-49d2-be5b-5c07585b8526")]
            public virtual RepoItemInfo tabOverViewInfo
            {
                get
                {
                    return _taboverviewInfo;
                }
            }

            /// <summary>
            /// The txtOVTLDatabases item.
            /// </summary>
            [RepositoryItem("b183b56d-66a9-42e1-b24d-657c5ff85e84")]
            public virtual Ranorex.Text txtOVTLDatabases
            {
                get
                {
                    return _txtovtldatabasesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtOVTLDatabases item info.
            /// </summary>
            [RepositoryItemInfo("b183b56d-66a9-42e1-b24d-657c5ff85e84")]
            public virtual RepoItemInfo txtOVTLDatabasesInfo
            {
                get
                {
                    return _txtovtldatabasesInfo;
                }
            }

            /// <summary>
            /// The txtQUEQHQuerySignature item.
            /// </summary>
            [RepositoryItem("1ac53496-5430-4106-be56-730602c18cbb")]
            public virtual Ranorex.Text txtQUEQHQuerySignature
            {
                get
                {
                    return _txtqueqhquerysignatureInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtQUEQHQuerySignature item info.
            /// </summary>
            [RepositoryItemInfo("1ac53496-5430-4106-be56-730602c18cbb")]
            public virtual RepoItemInfo txtQUEQHQuerySignatureInfo
            {
                get
                {
                    return _txtqueqhquerysignatureInfo;
                }
            }

            /// <summary>
            /// The tblQueryEventOccerrances item.
            /// </summary>
            [RepositoryItem("97717507-ac04-4b57-ad21-592e9f89d219")]
            public virtual Ranorex.Table tblQueryEventOccerrances
            {
                get
                {
                    return _tblqueryeventoccerrancesInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The tblQueryEventOccerrances item info.
            /// </summary>
            [RepositoryItemInfo("97717507-ac04-4b57-ad21-592e9f89d219")]
            public virtual RepoItemInfo tblQueryEventOccerrancesInfo
            {
                get
                {
                    return _tblqueryeventoccerrancesInfo;
                }
            }

            /// <summary>
            /// The btnQWQueryWaitsOverTime item.
            /// </summary>
            [RepositoryItem("4b9c1ef9-ca0e-4511-9555-ec765ea99f9f")]
            public virtual Ranorex.Button btnQWQueryWaitsOverTime
            {
                get
                {
                    return _btnqwquerywaitsovertimeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnQWQueryWaitsOverTime item info.
            /// </summary>
            [RepositoryItemInfo("4b9c1ef9-ca0e-4511-9555-ec765ea99f9f")]
            public virtual RepoItemInfo btnQWQueryWaitsOverTimeInfo
            {
                get
                {
                    return _btnqwquerywaitsovertimeInfo;
                }
            }

            /// <summary>
            /// The tblDBSSummary item.
            /// </summary>
            [RepositoryItem("a46dff0c-7ffe-4991-b4cc-be263d7d93ca")]
            public virtual Ranorex.Table tblDBSSummary
            {
                get
                {
                    return _tbldbssummaryInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The tblDBSSummary item info.
            /// </summary>
            [RepositoryItemInfo("a46dff0c-7ffe-4991-b4cc-be263d7d93ca")]
            public virtual RepoItemInfo tblDBSSummaryInfo
            {
                get
                {
                    return _tbldbssummaryInfo;
                }
            }

            /// <summary>
            /// The tblDBSTempDBSummary item.
            /// </summary>
            [RepositoryItem("7d37f544-3be8-4586-8b73-df846e0d5e68")]
            public virtual Ranorex.Table tblDBSTempDBSummary
            {
                get
                {
                    return _tbldbstempdbsummaryInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The tblDBSTempDBSummary item info.
            /// </summary>
            [RepositoryItemInfo("7d37f544-3be8-4586-8b73-df846e0d5e68")]
            public virtual RepoItemInfo tblDBSTempDBSummaryInfo
            {
                get
                {
                    return _tbldbstempdbsummaryInfo;
                }
            }

            /// <summary>
            /// The tblDBSConfiguration item.
            /// </summary>
            [RepositoryItem("195a2ec4-962e-4d2e-b2b7-76d747894459")]
            public virtual Ranorex.Table tblDBSConfiguration
            {
                get
                {
                    return _tbldbsconfigurationInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The tblDBSConfiguration item info.
            /// </summary>
            [RepositoryItemInfo("195a2ec4-962e-4d2e-b2b7-76d747894459")]
            public virtual RepoItemInfo tblDBSConfigurationInfo
            {
                get
                {
                    return _tbldbsconfigurationInfo;
                }
            }

            /// <summary>
            /// The tblDBSFiles item.
            /// </summary>
            [RepositoryItem("8dd4598b-05d8-4588-a263-3ca1bb8adc88")]
            public virtual Ranorex.Table tblDBSFiles
            {
                get
                {
                    return _tbldbsfilesInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The tblDBSFiles item info.
            /// </summary>
            [RepositoryItemInfo("8dd4598b-05d8-4588-a263-3ca1bb8adc88")]
            public virtual RepoItemInfo tblDBSFilesInfo
            {
                get
                {
                    return _tbldbsfilesInfo;
                }
            }

            /// <summary>
            /// The tblDBSTablesAndIndexes item.
            /// </summary>
            [RepositoryItem("00c0bfef-1197-4e2f-ae91-21982433f22a")]
            public virtual Ranorex.Table tblDBSTablesAndIndexes
            {
                get
                {
                    return _tbldbstablesandindexesInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The tblDBSTablesAndIndexes item info.
            /// </summary>
            [RepositoryItemInfo("00c0bfef-1197-4e2f-ae91-21982433f22a")]
            public virtual RepoItemInfo tblDBSTablesAndIndexesInfo
            {
                get
                {
                    return _tbldbstablesandindexesInfo;
                }
            }

            /// <summary>
            /// The tblDBSMirroring item.
            /// </summary>
            [RepositoryItem("cb330ad6-2a18-4c2f-828f-68d91269413d")]
            public virtual Ranorex.Table tblDBSMirroring
            {
                get
                {
                    return _tbldbsmirroringInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The tblDBSMirroring item info.
            /// </summary>
            [RepositoryItemInfo("cb330ad6-2a18-4c2f-828f-68d91269413d")]
            public virtual RepoItemInfo tblDBSMirroringInfo
            {
                get
                {
                    return _tbldbsmirroringInfo;
                }
            }

            /// <summary>
            /// The tblDBSBackupsAndRestores item.
            /// </summary>
            [RepositoryItem("44dd3d35-b3a1-4d64-b186-1a9a11f20642")]
            public virtual Ranorex.Table tblDBSBackupsAndRestores
            {
                get
                {
                    return _tbldbsbackupsandrestoresInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The tblDBSBackupsAndRestores item info.
            /// </summary>
            [RepositoryItemInfo("44dd3d35-b3a1-4d64-b186-1a9a11f20642")]
            public virtual RepoItemInfo tblDBSBackupsAndRestoresInfo
            {
                get
                {
                    return _tbldbsbackupsandrestoresInfo;
                }
            }

            /// <summary>
            /// The tblDBSServiceSummary item.
            /// </summary>
            [RepositoryItem("06f034e2-34f6-435b-9ed7-32dadab606c3")]
            public virtual Ranorex.Table tblDBSServiceSummary
            {
                get
                {
                    return _tbldbsservicesummaryInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The tblDBSServiceSummary item info.
            /// </summary>
            [RepositoryItemInfo("06f034e2-34f6-435b-9ed7-32dadab606c3")]
            public virtual RepoItemInfo tblDBSServiceSummaryInfo
            {
                get
                {
                    return _tbldbsservicesummaryInfo;
                }
            }

            /// <summary>
            /// The tblDBSServiceSqlAgentJobs item.
            /// </summary>
            [RepositoryItem("8d26c84a-cd04-4d47-a0ad-c92138d98a34")]
            public virtual Ranorex.Table tblDBSServiceSqlAgentJobs
            {
                get
                {
                    return _tbldbsservicesqlagentjobsInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The tblDBSServiceSqlAgentJobs item info.
            /// </summary>
            [RepositoryItemInfo("8d26c84a-cd04-4d47-a0ad-c92138d98a34")]
            public virtual RepoItemInfo tblDBSServiceSqlAgentJobsInfo
            {
                get
                {
                    return _tbldbsservicesqlagentjobsInfo;
                }
            }

            /// <summary>
            /// The tblDBSServicesJobHistory item.
            /// </summary>
            [RepositoryItem("9706d0c8-814f-4644-bd54-c8058e9ffe34")]
            public virtual Ranorex.Container tblDBSServicesJobHistory
            {
                get
                {
                    return _tbldbsservicesjobhistoryInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The tblDBSServicesJobHistory item info.
            /// </summary>
            [RepositoryItemInfo("9706d0c8-814f-4644-bd54-c8058e9ffe34")]
            public virtual RepoItemInfo tblDBSServicesJobHistoryInfo
            {
                get
                {
                    return _tbldbsservicesjobhistoryInfo;
                }
            }

            /// <summary>
            /// The OverViewTab folder.
            /// </summary>
            [RepositoryFolder("b4198f1b-1b59-48c6-abc4-9ecd0d0d6a75")]
            public virtual BVTRepoFolders.OverViewTabFolder OverViewTab
            {
                get { return _overviewtab; }
            }

            /// <summary>
            /// The QueriesTab folder.
            /// </summary>
            [RepositoryFolder("95f06b54-ee5d-42ee-951d-5c8c99f9e8e6")]
            public virtual BVTRepoFolders.QueriesTabFolder QueriesTab
            {
                get { return _queriestab; }
            }

            /// <summary>
            /// The DatabasesTab folder.
            /// </summary>
            [RepositoryFolder("6bc81376-9a3e-4f1d-9ad0-9cf4e4d3b4df")]
            public virtual BVTRepoFolders.DatabasesTabFolder DatabasesTab
            {
                get { return _databasestab; }
            }

            /// <summary>
            /// The View folder.
            /// </summary>
            [RepositoryFolder("fe7325d7-184c-4c5c-acdd-2b46aeca7cf0")]
            public virtual BVTRepoFolders.ViewFolder View
            {
                get { return _view; }
            }

            /// <summary>
            /// The ServicesTab folder.
            /// </summary>
            [RepositoryFolder("68c28ebf-8c92-4152-92ba-0e18414f85a3")]
            public virtual BVTRepoFolders.ServicesTabFolder ServicesTab
            {
                get { return _servicestab; }
            }
        }

        /// <summary>
        /// The OverViewTabFolder folder.
        /// </summary>
        [RepositoryFolder("b4198f1b-1b59-48c6-abc4-9ecd0d0d6a75")]
        public partial class OverViewTabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rgovdashboardInfo;
            RepoItemInfo _rgovdetailsInfo;
            RepoItemInfo _rgovconfigurationInfo;
            RepoItemInfo _rgovactivealertsInfo;
            RepoItemInfo _rgovtimelineInfo;

            /// <summary>
            /// Creates a new OverViewTab  folder.
            /// </summary>
            public OverViewTabFolder(RepoGenBaseFolder parentFolder) :
                    base("OverViewTab", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Overview']/toolbar[@automationid='overviewTabViewsGroup']", parentFolder, 30000, null, false, "b4198f1b-1b59-48c6-abc4-9ecd0d0d6a75", "")
            {
                _rgovdashboardInfo = new RepoItemInfo(this, "rgOVDashboard", ".//container[@caption='']/radiobutton[1]", 30000, null, "2236b86c-e275-4651-a7ab-4ba34c4cba50");
                _rgovdetailsInfo = new RepoItemInfo(this, "rgOVDetails", ".//container[@caption='']/radiobutton[2]", 30000, null, "beb74a52-7899-413a-aec6-db6ab2c34c7f");
                _rgovconfigurationInfo = new RepoItemInfo(this, "rgOVConfiguration", ".//container[@caption='']/radiobutton[3]", 30000, null, "4616c4b1-19c7-4090-bcf9-94e8a38b8797");
                _rgovactivealertsInfo = new RepoItemInfo(this, "rgOVActiveAlerts", ".//container[@caption='']/radiobutton[4]", 30000, null, "9e38cd1c-b090-4390-af5c-ae998e31ec2a");
                _rgovtimelineInfo = new RepoItemInfo(this, "rgOVTimeLine", ".//container[@caption='']/radiobutton[5]", 30000, null, "16d182e7-83b1-44c1-8708-f39926a9f9df");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b4198f1b-1b59-48c6-abc4-9ecd0d0d6a75")]
            public virtual Ranorex.ToolBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b4198f1b-1b59-48c6-abc4-9ecd0d0d6a75")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The rgOVDashboard item.
            /// </summary>
            [RepositoryItem("2236b86c-e275-4651-a7ab-4ba34c4cba50")]
            public virtual Ranorex.RadioButton rgOVDashboard
            {
                get
                {
                    return _rgovdashboardInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgOVDashboard item info.
            /// </summary>
            [RepositoryItemInfo("2236b86c-e275-4651-a7ab-4ba34c4cba50")]
            public virtual RepoItemInfo rgOVDashboardInfo
            {
                get
                {
                    return _rgovdashboardInfo;
                }
            }

            /// <summary>
            /// The rgOVDetails item.
            /// </summary>
            [RepositoryItem("beb74a52-7899-413a-aec6-db6ab2c34c7f")]
            public virtual Ranorex.RadioButton rgOVDetails
            {
                get
                {
                    return _rgovdetailsInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgOVDetails item info.
            /// </summary>
            [RepositoryItemInfo("beb74a52-7899-413a-aec6-db6ab2c34c7f")]
            public virtual RepoItemInfo rgOVDetailsInfo
            {
                get
                {
                    return _rgovdetailsInfo;
                }
            }

            /// <summary>
            /// The rgOVConfiguration item.
            /// </summary>
            [RepositoryItem("4616c4b1-19c7-4090-bcf9-94e8a38b8797")]
            public virtual Ranorex.RadioButton rgOVConfiguration
            {
                get
                {
                    return _rgovconfigurationInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgOVConfiguration item info.
            /// </summary>
            [RepositoryItemInfo("4616c4b1-19c7-4090-bcf9-94e8a38b8797")]
            public virtual RepoItemInfo rgOVConfigurationInfo
            {
                get
                {
                    return _rgovconfigurationInfo;
                }
            }

            /// <summary>
            /// The rgOVActiveAlerts item.
            /// </summary>
            [RepositoryItem("9e38cd1c-b090-4390-af5c-ae998e31ec2a")]
            public virtual Ranorex.RadioButton rgOVActiveAlerts
            {
                get
                {
                    return _rgovactivealertsInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgOVActiveAlerts item info.
            /// </summary>
            [RepositoryItemInfo("9e38cd1c-b090-4390-af5c-ae998e31ec2a")]
            public virtual RepoItemInfo rgOVActiveAlertsInfo
            {
                get
                {
                    return _rgovactivealertsInfo;
                }
            }

            /// <summary>
            /// The rgOVTimeLine item.
            /// </summary>
            [RepositoryItem("16d182e7-83b1-44c1-8708-f39926a9f9df")]
            public virtual Ranorex.RadioButton rgOVTimeLine
            {
                get
                {
                    return _rgovtimelineInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgOVTimeLine item info.
            /// </summary>
            [RepositoryItemInfo("16d182e7-83b1-44c1-8708-f39926a9f9df")]
            public virtual RepoItemInfo rgOVTimeLineInfo
            {
                get
                {
                    return _rgovtimelineInfo;
                }
            }
        }

        /// <summary>
        /// The QueriesTabFolder folder.
        /// </summary>
        [RepositoryFolder("95f06b54-ee5d-42ee-951d-5c8c99f9e8e6")]
        public partial class QueriesTabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rgquesignaturemodeInfo;
            RepoItemInfo _rgquestatementmodeInfo;
            RepoItemInfo _rgquequeryhistoryInfo;
            RepoItemInfo _rgquequerywaitsInfo;

            /// <summary>
            /// Creates a new QueriesTab  folder.
            /// </summary>
            public QueriesTabFolder(RepoGenBaseFolder parentFolder) :
                    base("QueriesTab", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Queries']/toolbar[@automationid='queriesTabViewsGroup']", parentFolder, 30000, null, false, "95f06b54-ee5d-42ee-951d-5c8c99f9e8e6", "")
            {
                _rgquesignaturemodeInfo = new RepoItemInfo(this, "rgQUESignatureMode", ".//container[@caption='']/radiobutton[1]", 30000, null, "7dd99cd2-b1a7-4a7c-9007-d91eff9643b7");
                _rgquestatementmodeInfo = new RepoItemInfo(this, "rgQUEStatementMode", "container[@caption='']/radiobutton[2]", 30000, null, "80c94682-d7e1-4252-8473-887e936b8134");
                _rgquequeryhistoryInfo = new RepoItemInfo(this, "rgQUEQueryHistory", "container[@caption='']/radiobutton[3]", 30000, null, "5e4d9ab4-26ec-4a32-8567-35290d1b5b50");
                _rgquequerywaitsInfo = new RepoItemInfo(this, "rgQUEQueryWaits", "container[@caption='']/radiobutton[4]", 30000, null, "64b1065c-660b-44a2-8e80-879274526008");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("95f06b54-ee5d-42ee-951d-5c8c99f9e8e6")]
            public virtual Ranorex.ToolBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("95f06b54-ee5d-42ee-951d-5c8c99f9e8e6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The rgQUESignatureMode item.
            /// </summary>
            [RepositoryItem("7dd99cd2-b1a7-4a7c-9007-d91eff9643b7")]
            public virtual Ranorex.RadioButton rgQUESignatureMode
            {
                get
                {
                    return _rgquesignaturemodeInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgQUESignatureMode item info.
            /// </summary>
            [RepositoryItemInfo("7dd99cd2-b1a7-4a7c-9007-d91eff9643b7")]
            public virtual RepoItemInfo rgQUESignatureModeInfo
            {
                get
                {
                    return _rgquesignaturemodeInfo;
                }
            }

            /// <summary>
            /// The rgQUEStatementMode item.
            /// </summary>
            [RepositoryItem("80c94682-d7e1-4252-8473-887e936b8134")]
            public virtual Ranorex.RadioButton rgQUEStatementMode
            {
                get
                {
                    return _rgquestatementmodeInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgQUEStatementMode item info.
            /// </summary>
            [RepositoryItemInfo("80c94682-d7e1-4252-8473-887e936b8134")]
            public virtual RepoItemInfo rgQUEStatementModeInfo
            {
                get
                {
                    return _rgquestatementmodeInfo;
                }
            }

            /// <summary>
            /// The rgQUEQueryHistory item.
            /// </summary>
            [RepositoryItem("5e4d9ab4-26ec-4a32-8567-35290d1b5b50")]
            public virtual Ranorex.RadioButton rgQUEQueryHistory
            {
                get
                {
                    return _rgquequeryhistoryInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgQUEQueryHistory item info.
            /// </summary>
            [RepositoryItemInfo("5e4d9ab4-26ec-4a32-8567-35290d1b5b50")]
            public virtual RepoItemInfo rgQUEQueryHistoryInfo
            {
                get
                {
                    return _rgquequeryhistoryInfo;
                }
            }

            /// <summary>
            /// The rgQUEQueryWaits item.
            /// </summary>
            [RepositoryItem("64b1065c-660b-44a2-8e80-879274526008")]
            public virtual Ranorex.RadioButton rgQUEQueryWaits
            {
                get
                {
                    return _rgquequerywaitsInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgQUEQueryWaits item info.
            /// </summary>
            [RepositoryItemInfo("64b1065c-660b-44a2-8e80-879274526008")]
            public virtual RepoItemInfo rgQUEQueryWaitsInfo
            {
                get
                {
                    return _rgquequerywaitsInfo;
                }
            }
        }

        /// <summary>
        /// The DatabasesTabFolder folder.
        /// </summary>
        [RepositoryFolder("6bc81376-9a3e-4f1d-9ad0-9cf4e4d3b4df")]
        public partial class DatabasesTabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rgdbsummaryInfo;
            RepoItemInfo _rgdbavailabillitygroupInfo;
            RepoItemInfo _rgdbtempdbsummaryInfo;
            RepoItemInfo _rgdbconfigurationInfo;
            RepoItemInfo _rgdbfilesInfo;
            RepoItemInfo _rgdbbackupsandrestoresInfo;
            RepoItemInfo _rgdbtablesandindexesInfo;
            RepoItemInfo _rgdbmirroringInfo;

            /// <summary>
            /// Creates a new DatabasesTab  folder.
            /// </summary>
            public DatabasesTabFolder(RepoGenBaseFolder parentFolder) :
                    base("DatabasesTab", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Databases']/toolbar[@automationid='databasesTabViewsGroup']", parentFolder, 30000, null, false, "6bc81376-9a3e-4f1d-9ad0-9cf4e4d3b4df", "")
            {
                _rgdbsummaryInfo = new RepoItemInfo(this, "rgDBSummary", ".//container[@caption='']/radiobutton[1]", 30000, null, "be671221-5fd4-4080-98ca-d4757e565a05");
                _rgdbavailabillitygroupInfo = new RepoItemInfo(this, "rgDBAvailabillityGroup", ".//container[@caption='']/radiobutton[2]", 30000, null, "24b488b6-7b3c-432e-bf70-7b76a2468c74");
                _rgdbtempdbsummaryInfo = new RepoItemInfo(this, "rgDBTempDBSummary", ".//container[@caption='']/radiobutton[3]", 30000, null, "f6b125b6-7085-4476-b325-e5a20a7779d1");
                _rgdbconfigurationInfo = new RepoItemInfo(this, "rgDBConfiguration", ".//container[@caption='']/radiobutton[4]", 30000, null, "e1614898-17f5-4a54-93dc-0c46cea8c173");
                _rgdbfilesInfo = new RepoItemInfo(this, "rgDBFiles", ".//container[@caption='']/radiobutton[5]", 30000, null, "0bea0d6f-7bb6-4183-a0c5-47027333d500");
                _rgdbbackupsandrestoresInfo = new RepoItemInfo(this, "rgDBBackupsAndRestores", ".//container[@caption='']/radiobutton[6]", 30000, null, "8c743482-1cd1-4375-ae22-f5eb007de01e");
                _rgdbtablesandindexesInfo = new RepoItemInfo(this, "rgDBTablesAndIndexes", ".//container[@caption='']/radiobutton[7]", 30000, null, "5eb32d53-29e0-4b07-8f17-5b52ebaede7f");
                _rgdbmirroringInfo = new RepoItemInfo(this, "rgDBMirroring", ".//container[@caption='']/radiobutton[8]", 30000, null, "9469a46a-abda-45fd-9152-0db10a601777");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6bc81376-9a3e-4f1d-9ad0-9cf4e4d3b4df")]
            public virtual Ranorex.ToolBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6bc81376-9a3e-4f1d-9ad0-9cf4e4d3b4df")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The rgDBSummary item.
            /// </summary>
            [RepositoryItem("be671221-5fd4-4080-98ca-d4757e565a05")]
            public virtual Ranorex.RadioButton rgDBSummary
            {
                get
                {
                    return _rgdbsummaryInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgDBSummary item info.
            /// </summary>
            [RepositoryItemInfo("be671221-5fd4-4080-98ca-d4757e565a05")]
            public virtual RepoItemInfo rgDBSummaryInfo
            {
                get
                {
                    return _rgdbsummaryInfo;
                }
            }

            /// <summary>
            /// The rgDBAvailabillityGroup item.
            /// </summary>
            [RepositoryItem("24b488b6-7b3c-432e-bf70-7b76a2468c74")]
            public virtual Ranorex.RadioButton rgDBAvailabillityGroup
            {
                get
                {
                    return _rgdbavailabillitygroupInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgDBAvailabillityGroup item info.
            /// </summary>
            [RepositoryItemInfo("24b488b6-7b3c-432e-bf70-7b76a2468c74")]
            public virtual RepoItemInfo rgDBAvailabillityGroupInfo
            {
                get
                {
                    return _rgdbavailabillitygroupInfo;
                }
            }

            /// <summary>
            /// The rgDBTempDBSummary item.
            /// </summary>
            [RepositoryItem("f6b125b6-7085-4476-b325-e5a20a7779d1")]
            public virtual Ranorex.RadioButton rgDBTempDBSummary
            {
                get
                {
                    return _rgdbtempdbsummaryInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgDBTempDBSummary item info.
            /// </summary>
            [RepositoryItemInfo("f6b125b6-7085-4476-b325-e5a20a7779d1")]
            public virtual RepoItemInfo rgDBTempDBSummaryInfo
            {
                get
                {
                    return _rgdbtempdbsummaryInfo;
                }
            }

            /// <summary>
            /// The rgDBConfiguration item.
            /// </summary>
            [RepositoryItem("e1614898-17f5-4a54-93dc-0c46cea8c173")]
            public virtual Ranorex.RadioButton rgDBConfiguration
            {
                get
                {
                    return _rgdbconfigurationInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgDBConfiguration item info.
            /// </summary>
            [RepositoryItemInfo("e1614898-17f5-4a54-93dc-0c46cea8c173")]
            public virtual RepoItemInfo rgDBConfigurationInfo
            {
                get
                {
                    return _rgdbconfigurationInfo;
                }
            }

            /// <summary>
            /// The rgDBFiles item.
            /// </summary>
            [RepositoryItem("0bea0d6f-7bb6-4183-a0c5-47027333d500")]
            public virtual Ranorex.RadioButton rgDBFiles
            {
                get
                {
                    return _rgdbfilesInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgDBFiles item info.
            /// </summary>
            [RepositoryItemInfo("0bea0d6f-7bb6-4183-a0c5-47027333d500")]
            public virtual RepoItemInfo rgDBFilesInfo
            {
                get
                {
                    return _rgdbfilesInfo;
                }
            }

            /// <summary>
            /// The rgDBBackupsAndRestores item.
            /// </summary>
            [RepositoryItem("8c743482-1cd1-4375-ae22-f5eb007de01e")]
            public virtual Ranorex.RadioButton rgDBBackupsAndRestores
            {
                get
                {
                    return _rgdbbackupsandrestoresInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgDBBackupsAndRestores item info.
            /// </summary>
            [RepositoryItemInfo("8c743482-1cd1-4375-ae22-f5eb007de01e")]
            public virtual RepoItemInfo rgDBBackupsAndRestoresInfo
            {
                get
                {
                    return _rgdbbackupsandrestoresInfo;
                }
            }

            /// <summary>
            /// The rgDBTablesAndIndexes item.
            /// </summary>
            [RepositoryItem("5eb32d53-29e0-4b07-8f17-5b52ebaede7f")]
            public virtual Ranorex.RadioButton rgDBTablesAndIndexes
            {
                get
                {
                    return _rgdbtablesandindexesInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgDBTablesAndIndexes item info.
            /// </summary>
            [RepositoryItemInfo("5eb32d53-29e0-4b07-8f17-5b52ebaede7f")]
            public virtual RepoItemInfo rgDBTablesAndIndexesInfo
            {
                get
                {
                    return _rgdbtablesandindexesInfo;
                }
            }

            /// <summary>
            /// The rgDBMirroring item.
            /// </summary>
            [RepositoryItem("9469a46a-abda-45fd-9152-0db10a601777")]
            public virtual Ranorex.RadioButton rgDBMirroring
            {
                get
                {
                    return _rgdbmirroringInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgDBMirroring item info.
            /// </summary>
            [RepositoryItemInfo("9469a46a-abda-45fd-9152-0db10a601777")]
            public virtual RepoItemInfo rgDBMirroringInfo
            {
                get
                {
                    return _rgdbmirroringInfo;
                }
            }
        }

        /// <summary>
        /// The ViewFolder folder.
        /// </summary>
        [RepositoryFolder("fe7325d7-184c-4c5c-acdd-2b46aeca7cf0")]
        public partial class ViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnovdbcpuInfo;
            RepoItemInfo _txtovcondetailsInfo;
            RepoItemInfo _txtovaadetailsInfo;
            RepoItemInfo _txtquesigmodeeventoccurrencesInfo;
            RepoItemInfo _tabqueqerywaitsInfo;
            RepoItemInfo _txtovdechartInfo;

            /// <summary>
            /// Creates a new View  folder.
            /// </summary>
            public ViewFolder(RepoGenBaseFolder parentFolder) :
                    base("View", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='viewHost']/container[@automationid='windowsFormsHostControl']", parentFolder, 30000, null, false, "fe7325d7-184c-4c5c-acdd-2b46aeca7cf0", "")
            {
                _btnovdbcpuInfo = new RepoItemInfo(this, "btnOVDBCPU", ".//container[@controlname='CpuControl']/toolbar[@controlname='dashboardHeaderStrip']/button[@accessiblename='CPU']", 30000, null, "ee9dd84e-30a5-42eb-ac9d-9307df06d215");
                _txtovcondetailsInfo = new RepoItemInfo(this, "txtOVCONDetails", ".//container[@controlname='ServerConfigurationView']//toolbar[@controlname='detailsHeaderStrip']/text[@accessiblename='Details']", 30000, null, "07032821-6fe8-47f7-883c-6b58c53bdf66");
                _txtovaadetailsInfo = new RepoItemInfo(this, "txtOVAADetails", ".//container[@controlname='ActiveAlertsView']//toolbar[@controlname='detailsHeaderStrip']/text[@accessiblename='Details']", 30000, null, "5537519e-ad66-4f73-b15c-9f4ac7aeb0b3");
                _txtquesigmodeeventoccurrencesInfo = new RepoItemInfo(this, "txtQUESIGMODEEventOccurrences", ".//toolbar[@controlname='queryMonitorGridHeaderStrip']/text[@accessiblename='Event Occurrences']", 30000, null, "fddebd24-6883-4669-bce3-18c7b5b4ba44");
                _tabqueqerywaitsInfo = new RepoItemInfo(this, "tabQUEQeryWaits", ".//tabpagelist[@accessiblerole='PageTabList']/tabpage[@accessiblename='Waits']", 30000, null, "2570b7ff-c43f-46a9-85ce-c60e1ba9f17b");
                _txtovdechartInfo = new RepoItemInfo(this, "txtOVDEChart", ".//container[@controlname='_child']/container[@controlname='ServerDetailsView']//toolbar[@controlname='chartHeaderStrip']/text[@accessiblename='Chart']", 30000, null, "8e3a64c3-cdb6-4327-b070-4726320de259");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fe7325d7-184c-4c5c-acdd-2b46aeca7cf0")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fe7325d7-184c-4c5c-acdd-2b46aeca7cf0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnOVDBCPU item.
            /// </summary>
            [RepositoryItem("ee9dd84e-30a5-42eb-ac9d-9307df06d215")]
            public virtual Ranorex.Button btnOVDBCPU
            {
                get
                {
                    return _btnovdbcpuInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOVDBCPU item info.
            /// </summary>
            [RepositoryItemInfo("ee9dd84e-30a5-42eb-ac9d-9307df06d215")]
            public virtual RepoItemInfo btnOVDBCPUInfo
            {
                get
                {
                    return _btnovdbcpuInfo;
                }
            }

            /// <summary>
            /// The txtOVCONDetails item.
            /// </summary>
            [RepositoryItem("07032821-6fe8-47f7-883c-6b58c53bdf66")]
            public virtual Ranorex.Text txtOVCONDetails
            {
                get
                {
                    return _txtovcondetailsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtOVCONDetails item info.
            /// </summary>
            [RepositoryItemInfo("07032821-6fe8-47f7-883c-6b58c53bdf66")]
            public virtual RepoItemInfo txtOVCONDetailsInfo
            {
                get
                {
                    return _txtovcondetailsInfo;
                }
            }

            /// <summary>
            /// The txtOVAADetails item.
            /// </summary>
            [RepositoryItem("5537519e-ad66-4f73-b15c-9f4ac7aeb0b3")]
            public virtual Ranorex.Text txtOVAADetails
            {
                get
                {
                    return _txtovaadetailsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtOVAADetails item info.
            /// </summary>
            [RepositoryItemInfo("5537519e-ad66-4f73-b15c-9f4ac7aeb0b3")]
            public virtual RepoItemInfo txtOVAADetailsInfo
            {
                get
                {
                    return _txtovaadetailsInfo;
                }
            }

            /// <summary>
            /// The txtQUESIGMODEEventOccurrences item.
            /// </summary>
            [RepositoryItem("fddebd24-6883-4669-bce3-18c7b5b4ba44")]
            public virtual Ranorex.Text txtQUESIGMODEEventOccurrences
            {
                get
                {
                    return _txtquesigmodeeventoccurrencesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtQUESIGMODEEventOccurrences item info.
            /// </summary>
            [RepositoryItemInfo("fddebd24-6883-4669-bce3-18c7b5b4ba44")]
            public virtual RepoItemInfo txtQUESIGMODEEventOccurrencesInfo
            {
                get
                {
                    return _txtquesigmodeeventoccurrencesInfo;
                }
            }

            /// <summary>
            /// The tabQUEQeryWaits item.
            /// </summary>
            [RepositoryItem("2570b7ff-c43f-46a9-85ce-c60e1ba9f17b")]
            public virtual Ranorex.TabPage tabQUEQeryWaits
            {
                get
                {
                    return _tabqueqerywaitsInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tabQUEQeryWaits item info.
            /// </summary>
            [RepositoryItemInfo("2570b7ff-c43f-46a9-85ce-c60e1ba9f17b")]
            public virtual RepoItemInfo tabQUEQeryWaitsInfo
            {
                get
                {
                    return _tabqueqerywaitsInfo;
                }
            }

            /// <summary>
            /// The txtOVDEChart item.
            /// </summary>
            [RepositoryItem("8e3a64c3-cdb6-4327-b070-4726320de259")]
            public virtual Ranorex.Text txtOVDEChart
            {
                get
                {
                    return _txtovdechartInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtOVDEChart item info.
            /// </summary>
            [RepositoryItemInfo("8e3a64c3-cdb6-4327-b070-4726320de259")]
            public virtual RepoItemInfo txtOVDEChartInfo
            {
                get
                {
                    return _txtovdechartInfo;
                }
            }
        }

        /// <summary>
        /// The ServicesTabFolder folder.
        /// </summary>
        [RepositoryFolder("68c28ebf-8c92-4152-92ba-0e18414f85a3")]
        public partial class ServicesTabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rgsersummaryInfo;
            RepoItemInfo _rgsersqlagentjobsInfo;

            /// <summary>
            /// Creates a new ServicesTab  folder.
            /// </summary>
            public ServicesTabFolder(RepoGenBaseFolder parentFolder) :
                    base("ServicesTab", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Services']/toolbar[@automationid='servicesTabViewsGroup']", parentFolder, 30000, null, false, "68c28ebf-8c92-4152-92ba-0e18414f85a3", "")
            {
                _rgsersummaryInfo = new RepoItemInfo(this, "rgSERSummary", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Services']/toolbar[@automationid='servicesTabViewsGroup']/container[@caption='']/radiobutton[1]", 30000, null, "0488712f-bc6c-43c7-8521-409d62190f17");
                _rgsersqlagentjobsInfo = new RepoItemInfo(this, "rgSERSqlAgentJobs", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Services']/toolbar[@automationid='servicesTabViewsGroup']/container[@caption='']/radiobutton[2]", 30000, null, "cae5e8ec-faca-4ec8-a32e-da06214a7d71");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("68c28ebf-8c92-4152-92ba-0e18414f85a3")]
            public virtual Ranorex.ToolBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("68c28ebf-8c92-4152-92ba-0e18414f85a3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The rgSERSummary item.
            /// </summary>
            [RepositoryItem("0488712f-bc6c-43c7-8521-409d62190f17")]
            public virtual Ranorex.RadioButton rgSERSummary
            {
                get
                {
                    return _rgsersummaryInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgSERSummary item info.
            /// </summary>
            [RepositoryItemInfo("0488712f-bc6c-43c7-8521-409d62190f17")]
            public virtual RepoItemInfo rgSERSummaryInfo
            {
                get
                {
                    return _rgsersummaryInfo;
                }
            }

            /// <summary>
            /// The rgSERSqlAgentJobs item.
            /// </summary>
            [RepositoryItem("cae5e8ec-faca-4ec8-a32e-da06214a7d71")]
            public virtual Ranorex.RadioButton rgSERSqlAgentJobs
            {
                get
                {
                    return _rgsersqlagentjobsInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgSERSqlAgentJobs item info.
            /// </summary>
            [RepositoryItemInfo("cae5e8ec-faca-4ec8-a32e-da06214a7d71")]
            public virtual RepoItemInfo rgSERSqlAgentJobsInfo
            {
                get
                {
                    return _rgsersqlagentjobsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}